---
version: 0.2

env:
  variables:
    mktip_var: "AWSCODEBUILDSPEC"
  paramter-store:
    nuget_user: "test-nuget-username"
    nuget_password: "test-nuget-password"
    nuget_feed_value: "test-nuget-feed-value"

phases:
  install:
    runtime-versions:
      docker: 18
      dotnet: 2.2

  build:
    commands:
      - echo Setting up vsts access files...
      - echo $mktip_var
      - echo $nuget_feed_value
      - ./test.sh $nuget_feed_value $nuget_user $nuget_password
  post_build:
    commands:
      - echo Successfully completed the build on `date`.
