---
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      dotnet: 2.2
  pre_build:
    commands:
      - ./test.sh

  build:
    commands:
      - echo Setting up vsts access files...
      - cat nuget.config
  post_build:
    commands:
      - echo Successfully completed the build on `date`.
